name: SLSA Provenance
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  provenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'dist/*'
